name: sdp-project-ci-cd

on:
  push:
    branches:
      - main
    
jobs:
  deploy-dev:
    name: Deploy to DEV
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy to dev
        run: databricks bundle deploy -t dev
    
  run-tests:
    name: Run unit-tests
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pytest pyspark
      - name: Run Tests
        run: pytest databricks/tests/

  deploy-prod:
    name: Deploy to Prod
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}

    runs-on: ubuntu-latest
    environment: prod 
    needs: run-tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy to prod
        run: databricks bundle deploy -t prod
      
  run-prod-pipeline:
    name: Run Prod ETL Job
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
    runs-on: ubuntu-latest
    needs: deploy-prod
    steps:
      - uses: actions/checkout@v4
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main       
      - name: Run ETL Pipeline
        run: databricks bundle run sdp_ecommerce_job --full-refresh-all --no-wait -t prod
  
